config/routes.rb
Rails.application.routes.draw do
  get "upload" => 'images#new', as: "upload"

  get 'images/create'

  get 'images/destroy'

  root 'images#index'

  get 'categories/new'

  get 'categories/create'

  get 'categories/edit'

  get 'categories/update'

  get 'categories/destroy'

  get 'categories/show'

  resources :images, :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :category

  mount_uploader :image, ImageUploader

  before_save :update_image_attributes

  private
    def update_image_attributes
      if image.present? && image_changed?
        self.image_content_type = image.file.content_type
        self.image_file_size = image.file.size
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :getCategoryNav
  protect_from_forgery with: :exception

  private
    def getCategoryNav
      @categoryNav = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Categoría agregada"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all
    @category = Category.find(params[:id])
    @images = @category.images
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Categoría actualizada"
      redirect_to category_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:notice] = "Imagen agregada"
      redirect_to images_path
    else
      render 'new'
    end
  end

  def destroy
    @image = Image.find(params[:id])
    if @image.destroy
      flash[:notice] = "Imagen eliminada"
      redirect_to images_path
    else
      flash[:alert] = "La imagen no pudo ser aliminada"
      redirect_to images_path
    end
  end

  def index
    @images = Image.all
    @categories = Category.all
  end

  private
    def image_params
      params.require(:image).permit(:image_title, :image, :category_id, :image_description,
      :image_file_size, :image_content_type, :remote_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/edit.html.erb
<h2>Editar categoría</h2>
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_message.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Actualizar", class:"btn btn-primary" %>
  <%= link_to "Cancelar", categories_path, class:"btn btn-default" %>
<% end %>
<h3 class="page-header">Imagenes en <%= @category.name %></h3>
<div id="edit_images">
  <% @images.each_slice(6) do |image| %>
    <div class="row">
      <% image.each do |image| %>
        <div class="col-md-2">
          <%= image_tag image.image_url(:thumb) %>
          <center><%= link_to "Eliminar", image_path(image), class:'delete',
          method: :delete, data: { confirm: "Estas seguro?" } %></center>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h2>Agregar categoría</h2>
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_message.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <br>
  <%= f.submit "Agregar", class:"btn btn-primary" %>
  <%= link_to "Cancelar", categories_path, class:"btn btn-default" %>
<% end %>

app/views/categories/show.html.erb
<div id="gallery">
  <h2><%= @category.name %> <small class="pull-right">
    <%= link_to "Editar", edit_category_path %>
  </small></%></h2>
  <% @images.each_slice(4) do |image| %>
    <div class="row">
      <% image.each do |image| %>
        <div class="col-md-3">
          <div class="photo photo-type-line">
            <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="<%= image.category.name %>"
            data-title="<%= image.image_title %>">
              <div class="photo-info">
                <div class="headline"><%= image.image_title %></div>
                <div class="line"></div>
                <div class="desc">
                  <%= image.image_description %>
                </div>
                <div class="mask"></div>
              </div>
            </a>
            <div class="photo-img">
              <%= image_tag image.image_url(:thumb) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/images/index.html.erb
<div id="gallery">
  <h2>Todas las imagenes</h2>
  <% @images.each_slice(4) do |image| %>
    <div class="row">
      <% image.each do |image| %>
        <div class="col-md-3">
          <div class="photo photo-type-line">
            <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="<%= image.category.name %>"
            data-title="<%= image.image_title %>">
              <div class="photo-info">
                <div class="headline"><%= image.image_title %></div>
                <div class="line"></div>
                <div class="desc">
                  <%= image.image_description %>
                </div>
                <div class="mask"></div>
              </div>
            </a>
            <div class="photo-img">
              <%= image_tag image.image_url(:thumb) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/images/new.html.erb
<h2>Subir imagen</h2>
<%= form_for @image, html: { multipart: true } do |f| %>
  <% if @image.errors.any? %>
    <% @image.errors.full_message.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :image_title, "Titulo" %>
    <%= f.text_field :image_title, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category, "Categoría" %><br/>
    <%= f.select :category_id, Category.all.collect { |x| [x.name, x.id] },
        { :include_blank => 'Elige una' }, class:'form-control' %><br/>
  </div>
  <div class="form-group">
    <%= f.label :image_description, "Descripción" %>
    <%= f.text_area :image_description, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <br>
  <%= f.submit "Agregar", class:'btn btn-primary' %>
  <%= link_to "Cancelar", images_path, class:'btn btn-default' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TICS | Galaría</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Galeria TICS</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Inicio", root_path %></li>
            <% @categoryNav.each do |category| %>
              <li><%= link_to category.name, category_path(category.id) %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "Subir imagen", upload_path %></li>
            <li><%= link_to "Agregar categoría", new_category_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    <section>
      <div class="container">
        <% if flash[:notice] %>
          <div class="alert alert-success">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <% if flash[:alert] %>
          <div class="alert alert-danger">
            <%= flash[:alert] %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </section>
    <footer>
      <p>Jorge Castillo Diaz 605</p>
    </footer>
  </body>
</html>